//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.15 at 06:51:32 PM IST 
//


package com.q9.bat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batInfo" type="{http://www.q9.com/bat}batInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batInfo"
})
@XmlRootElement(name = "getBatByIdResponse")
public class GetBatByIdResponse {

    @XmlElement(required = true)
    protected BatInfo batInfo;

    /**
     * Gets the value of the batInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BatInfo }
     *     
     */
    public BatInfo getBatInfo() {
        return batInfo;
    }

    /**
     * Sets the value of the batInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatInfo }
     *     
     */
    public void setBatInfo(BatInfo value) {
        this.batInfo = value;
    }

}
