//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.15 at 06:51:32 PM IST 
//


package com.q9.bat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.q9.bat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.q9.bat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateBatByIdResponse }
     * 
     */
    public UpdateBatByIdResponse createUpdateBatByIdResponse() {
        return new UpdateBatByIdResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdateBatByIdRequest }
     * 
     */
    public UpdateBatByIdRequest createUpdateBatByIdRequest() {
        return new UpdateBatByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteBatByIdResponse }
     * 
     */
    public DeleteBatByIdResponse createDeleteBatByIdResponse() {
        return new DeleteBatByIdResponse();
    }

    /**
     * Create an instance of {@link BatDetailsRequest }
     * 
     */
    public BatDetailsRequest createBatDetailsRequest() {
        return new BatDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteBatByIdRequest }
     * 
     */
    public DeleteBatByIdRequest createDeleteBatByIdRequest() {
        return new DeleteBatByIdRequest();
    }

    /**
     * Create an instance of {@link GetBatByIdRequest }
     * 
     */
    public GetBatByIdRequest createGetBatByIdRequest() {
        return new GetBatByIdRequest();
    }

    /**
     * Create an instance of {@link GetBatByIdResponse }
     * 
     */
    public GetBatByIdResponse createGetBatByIdResponse() {
        return new GetBatByIdResponse();
    }

    /**
     * Create an instance of {@link BatInfo }
     * 
     */
    public BatInfo createBatInfo() {
        return new BatInfo();
    }

    /**
     * Create an instance of {@link BatDetailsResponse }
     * 
     */
    public BatDetailsResponse createBatDetailsResponse() {
        return new BatDetailsResponse();
    }

    /**
     * Create an instance of {@link Bat }
     * 
     */
    public Bat createBat() {
        return new Bat();
    }

}
